### ISSUE TITLE
Template execution error

### ISSUE THREAD

**Issue by tbrog** [ese-unibe-ch/ese2010-team3#95]
Wenn Spam markiert wird und man dann mit Jack auf Benachrichtigungen geht komm dieser Fehler.

<code>play.exceptions.TemplateExecutionException: No signature of method: models.Question.getQuestion() is applicable for argument types: () values: []
    at play.templates.Template.throwException(Template.java:296)
    at play.templates.Template.render(Template.java:261)
    at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:22)
    at play.mvc.Controller.renderTemplate(Controller.java:489)
    at play.mvc.Controller.render(Controller.java:521)
    at controllers.Application.notifications(Application.java:362)
    at play.utils.Java.invokeStatic(Java.java:129)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:139)
    at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.MissingMethodException: No signature of method: models.Question.getQuestion() is applicable for argument types: () values: []
    at /app/views/Application/notifications.html.(line:21)
    at play.templates.Template.render(Template.java:238)

</code>

**Comment by sbuenzli** [comment]
Das sollte mit folgender Änderung geflickt sein: https://github.com/ese-unibe-ch/ese2010-team3/commit/c208f985406abce572e19dd01770088a0b4edabf#L0R360 (damit werden Spam-Meldungen nicht mehr mit Antwort-Benachrichtigungen vermischt).
